#include "motor.h"
#include "pwm.h"

void Motor_GPIO_Cfg(void)
{
  GPIO_InitTypeDef  GPIO_InitStructure;
	/* Common configuration for all pins */
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;					//普通输出模式
  GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;				//推挽输出
  GPIO_InitStructure.GPIO_Speed = GPIO_Speed_100MHz;		//100MHz
  GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_NOPULL;

	
	//01号电机控制线
	RCC_AHB1PeriphClockCmd(MOTOR_CONTROL_01_CLK, ENABLE);
	GPIO_InitStructure.GPIO_Pin      =    MOTOR_CONTROL_01_PIN;
  GPIO_Init(MOTOR_CONTROL_01_PORT, &GPIO_InitStructure);
	
	//02号电机控制线
	RCC_AHB1PeriphClockCmd(MOTOR_CONTROL_02_CLK, ENABLE);
	GPIO_InitStructure.GPIO_Pin      =    MOTOR_CONTROL_02_PIN;
  GPIO_Init(MOTOR_CONTROL_02_PORT, &GPIO_InitStructure);
	
	//03号电机控制线
	RCC_AHB1PeriphClockCmd(MOTOR_CONTROL_03_CLK, ENABLE);
	GPIO_InitStructure.GPIO_Pin      =    MOTOR_CONTROL_03_PIN;
  GPIO_Init(MOTOR_CONTROL_03_PORT, &GPIO_InitStructure);
	
	//04号电机控制线
	RCC_AHB1PeriphClockCmd(MOTOR_CONTROL_04_CLK, ENABLE);
	GPIO_InitStructure.GPIO_Pin      =    MOTOR_CONTROL_04_PIN;
  GPIO_Init(MOTOR_CONTROL_04_PORT, &GPIO_InitStructure);

}

void MOTOR_GO_STOP(void)
{
	GPIO_ResetBits(MOTOR_CONTROL_01_PORT,MOTOR_CONTROL_01_PIN);			//PC8
	GPIO_ResetBits(MOTOR_CONTROL_02_PORT,MOTOR_CONTROL_02_PIN);			//PC9
	GPIO_ResetBits(MOTOR_CONTROL_03_PORT,MOTOR_CONTROL_03_PIN);			//PD14
	GPIO_ResetBits(MOTOR_CONTROL_04_PORT,MOTOR_CONTROL_04_PIN);			//PD15
	TIM_Cmd(TIM2, DISABLE);
}

void MOTOR_FORWARD(void)
{
	MOTOR_GO_STOP();
	PWM_MOTOR_Cfg();
	GPIO_SetBits(MOTOR_CONTROL_03_PORT,MOTOR_CONTROL_03_PIN);			//PD14
	GPIO_SetBits(MOTOR_CONTROL_01_PORT,MOTOR_CONTROL_01_PIN);			//PC8
	GPIO_ResetBits(MOTOR_CONTROL_04_PORT,MOTOR_CONTROL_04_PIN);			//PD15	
	GPIO_ResetBits(MOTOR_CONTROL_02_PORT,MOTOR_CONTROL_02_PIN);			//PC9
}
void MOTOR_BACK(void)
{
	MOTOR_GO_STOP();
  PWM_MOTOR_Cfg();
	GPIO_SetBits(MOTOR_CONTROL_04_PORT,MOTOR_CONTROL_04_PIN);			//PD15	
	GPIO_SetBits(MOTOR_CONTROL_02_PORT,MOTOR_CONTROL_02_PIN);			//PC9
	GPIO_ResetBits(MOTOR_CONTROL_03_PORT,MOTOR_CONTROL_03_PIN);			//PD14
	GPIO_ResetBits(MOTOR_CONTROL_01_PORT,MOTOR_CONTROL_01_PIN);			//PC8
	
  
}
void MOTOR_LEFT(void)
{
	MOTOR_GO_STOP();
	PWM_MOTOR_Cfg();
	GPIO_SetBits(MOTOR_CONTROL_01_PORT,MOTOR_CONTROL_01_PIN);			//PC8	
	GPIO_ResetBits(MOTOR_CONTROL_04_PORT,MOTOR_CONTROL_04_PIN);			//PD15	
	GPIO_ResetBits(MOTOR_CONTROL_02_PORT,MOTOR_CONTROL_02_PIN);			//PC9	
	GPIO_ResetBits(MOTOR_CONTROL_03_PORT,MOTOR_CONTROL_03_PIN);			//PD14  
}
void MOTOR_RIGHT(void)
{
	MOTOR_GO_STOP();
	PWM_MOTOR_Cfg();
	GPIO_SetBits(MOTOR_CONTROL_03_PORT,MOTOR_CONTROL_03_PIN);			//PD14 	
	GPIO_ResetBits(MOTOR_CONTROL_01_PORT,MOTOR_CONTROL_01_PIN);			//PC8	
	GPIO_ResetBits(MOTOR_CONTROL_04_PORT,MOTOR_CONTROL_04_PIN);			//PD15	
	GPIO_ResetBits(MOTOR_CONTROL_02_PORT,MOTOR_CONTROL_02_PIN);			//PC9	
}
//以下四种情况的驱动要再调试后才能确定
void MOTOR_LEFT_FORWARD(void)
{
	MOTOR_GO_STOP();
	PWM_MOTOR_Cfg();
	GPIO_SetBits(MOTOR_CONTROL_03_PORT,MOTOR_CONTROL_03_PIN);			//PD14 	
	GPIO_SetBits(MOTOR_CONTROL_01_PORT,MOTOR_CONTROL_01_PIN);			//PC8	
	GPIO_ResetBits(MOTOR_CONTROL_04_PORT,MOTOR_CONTROL_04_PIN);			//PD15	
	GPIO_ResetBits(MOTOR_CONTROL_02_PORT,MOTOR_CONTROL_02_PIN);			//PC9

}
void MOTOR_RIGHT_FORWARD(void)
{
	MOTOR_GO_STOP();
	PWM_MOTOR_Cfg();
	GPIO_ResetBits(MOTOR_CONTROL_03_PORT,MOTOR_CONTROL_03_PIN);			//PD14 	
	GPIO_ResetBits(MOTOR_CONTROL_01_PORT,MOTOR_CONTROL_01_PIN);			//PC8	
	GPIO_SetBits(MOTOR_CONTROL_04_PORT,MOTOR_CONTROL_04_PIN);			//PD15	
	GPIO_SetBits(MOTOR_CONTROL_02_PORT,MOTOR_CONTROL_02_PIN);			//PC9
	
}
void MOTOR_LEFT_BACK(void)
{
	MOTOR_GO_STOP();
	PWM_MOTOR_Cfg();
	GPIO_SetBits(MOTOR_CONTROL_04_PORT,MOTOR_CONTROL_04_PIN);			//PD15	
	GPIO_SetBits(MOTOR_CONTROL_02_PORT,MOTOR_CONTROL_02_PIN);			//PC9
	GPIO_ResetBits(MOTOR_CONTROL_03_PORT,MOTOR_CONTROL_03_PIN);			//PD14 	
	GPIO_ResetBits(MOTOR_CONTROL_01_PORT,MOTOR_CONTROL_01_PIN);			//PC8	
	

}
void MOTOR_RIGHT_BACK(void)
{
	MOTOR_GO_STOP();
	PWM_MOTOR_Cfg();
	GPIO_SetBits(MOTOR_CONTROL_04_PORT,MOTOR_CONTROL_04_PIN);			//PD15	
	GPIO_SetBits(MOTOR_CONTROL_02_PORT,MOTOR_CONTROL_02_PIN);			//PC9
	GPIO_ResetBits(MOTOR_CONTROL_03_PORT,MOTOR_CONTROL_03_PIN);			//PD14 	
	GPIO_ResetBits(MOTOR_CONTROL_01_PORT,MOTOR_CONTROL_01_PIN);			//PC8	

}






